### ISSUE TITLE
Can you provide me with the floating wind turbine model for SIMA version 4.2?

### ISSUE THREAD

**Issue by tatesnow** [SINTEF/sima-examples-site#1]
Thank you very much for sharing the case! Can you provide me with the floating wind turbine model for SIMA version 4.2, because I only have SIMA software version 4.2! Thank you very much for your help!

**Comment by lassebje** [comment]
Hi! Do you mean in addition to the examples provided in the main Help-menu?
![image](https://user-images.githubusercontent.com/2123120/217467863-d39540c6-d4de-46cd-8bcd-5bd88d5baf76.png)

**Comment by tatesnow** [comment]
Thank you very much! @lassebje I know there are several models in HELP center, but I want to download the two IEA 15MW models mentioned in this link https://sintef.github.io/sima-examples-site/examples/SIMA_4.4/examples.html

![image](https://user-images.githubusercontent.com/42032942/217990345-16838f12-55ad-4325-a72e-abe15d0f5d9f.png)

**Comment by tatesnow** [comment]
If you have other models of floating wind turbines that you can provide to me, I am also in urgent need

**Comment by lassebje** [comment]
I am sorry, but these draft examples are only valid in SIMA 4.4 and backporting to SIMA 4.2 is not a small job, nor recommended as the controller functionality in 4.2 really isn't sufficient to support these new turbines. I think upgrading to 4.4 is the only option here

**Comment by tatesnow** [comment]
okay, thank you very much!
